trigger:
 branches:
   include:
     - main
     - feature/*

pool: 
  name: Jasus

variables:
  svc: 'newpipeline'  
  subsid: 'c69268aa-c88b-494c-aa80-775984104d2a'

stages:
  - stage: terraformplanning
    condition: or(eq(variables['Build.SourceBranchName'], 'main'), startsWith(variables['Build.SourceBranchName'], 'feature/'))
    displayName: Terraform planning
    jobs:
      - job: planning
        displayName: planning
        steps:
          - task: TerraformInstaller@1
            displayName: terraform install
            inputs:
              terraformVersion: latest
          - task: TerraformTask@5
            displayName: terraform init
            inputs:
              provider: azurerm
              command: init
              backendAzureRmUseEntraIdForAuthentication: false
              backendServiceArm: '$(svc)'
              backendAzureRmOverrideSubscriptionID: '$(subsid)'
              backendAzureRmResourceGroupName: 'rg-gunjan-cicd'
              backendAzureRmStorageAccountName: 'xyzabcdefgh'
              backendAzureRmContainerName: 'brijesh1'
              backendAzureRmKey: 'raman.tfstate'

          - task: TerraformTask@5
            displayName: terraform plan
            inputs:
              provider: azurerm
              command: plan
              environmentServiceNameAzureRM: newpipeline


  - stage: 
    displayName: apply
    dependsOn: terraformplanning
    condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'main'))
    jobs:
      - job: Apply
        displayName: apply
        steps:
          - task: TerraformInstaller@1
            inputs:
              terraformVersion: latest

          - task: TerraformTask@5  
            displayName: terraform Init
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendAzureRmUseEntraIdForAuthentication: false
              backendServiceArm: '$(svc)'
              backendAzureRmOverrideSubscriptionID: '$(subsid)'
              backendAzureRmResourceGroupName: 'rg-gunjan-cicd'
              backendAzureRmStorageAccountName: 'xyzabcdefgh'
              backendAzureRmContainerName: 'brijesh1'
              backendAzureRmKey: 'raman.tfstate'
          - task: TerraformTask@5
            displayName: terraform apply
            # condition: ${{parameters.apply}}
            inputs:
              provider: azurerm
              command: apply
              environmentServiceNameAzureRM: '$(svc)'

