trigger:
  branches:
    include:
      - main
      - feature/*

pool:
  name: Jasus

variables:
  svc: 'newpipeline'  
  subsid: 'c69268aa-c88b-494c-aa80-775984104d2a'

stages:
  - stage: planning
    displayName: terraform plan stage
    condition: or(eq(variables['Build.SourceBranchName'], 'main'), startsWith(variables['Build.SourceBranchName'], 'feature/'))
    jobs:
      - job: planning
        displayName: planning job
        steps:
          - task: TerraformInstaller@1
            displayName: terraform installer
            inputs:
              terraformVersion: latest

          - task: TerraformTask@5  
            displayName: terraform Init
            # condition: ${{parameters.init}}
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendAzureRmUseEntraIdForAuthentication: false
              backendServiceArm: $(svc)
              backendAzureRmOverrideSubscriptionID: $(subsid)
              backendAzureRmResourceGroupName: 'rg-gunjan-cicd'
              backendAzureRmStorageAccountName: 'xyzabcdefgh'
              backendAzureRmContainerName: 'brijesh1'
              backendAzureRmKey: 'raman.tfstate'

          - task: TerraformTask@5
            displayName: terraform Plan
            # condition: '${{parameters.plan}}'
            inputs:
              provider: azurerm
              command: plan
              environmentServiceNameAzureRM: '$(svc)'

                 
         
  - stage: validationandplan
    pool: server
    displayName: validation
    jobs:
      - job: validation
        displayName: validation
        steps:
          - task: ManualValidation@1
            displayName: manualvalidate
            inputs:
              notifyUsers: 'Brijesh@psutar43gmail.onmicrosoft.com'
              allowApproversToApproveTheirOwnRuns: false
              
  - stage: 
    displayName: apply
    dependsOn: planning
    condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'main'))
    jobs:
      - job: Apply
        displayName: apply
        steps:
          - task: TerraformInstaller@1
            inputs:
              terraformVersion: latest

          - task: TerraformTask@5  
            displayName: terraform Init
            # condition: ${{parameters.init}}
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendAzureRmUseEntraIdForAuthentication: false
              backendServiceArm: '$(svc)'
              backendAzureRmOverrideSubscriptionID: '$(subsid)'
              backendAzureRmResourceGroupName: 'rg-gunjan-cicd'
              backendAzureRmStorageAccountName: 'xyzabcdefgh'
              backendAzureRmContainerName: 'brijesh1'
              backendAzureRmKey: 'raman.tfstate'
          - task: TerraformTask@5
            displayName: terraform apply
            # condition: ${{parameters.apply}}
            inputs:
              provider: azurerm
              command: apply
              environmentServiceNameAzureRM: '$(svc)'
                  
              

                  
    