trigger:
- main

pool:
  name: Jasus

stages:
  - stage: Planning
    displayName: planning
    jobs: 
      - job: terrraform
        displayName: terraform installer
        steps:
          - task: TerraformInstaller@1
            displayName: terraform install
            inputs:
              terraformVersion: latest

          - task: TerraformTask@5
            displayName: Terraform Init
            inputs:
              provider: 'azurerm'
              command: init
              backendAzureRmUseEntraIdForAuthentication: false
              backendServiceArm: 'newpipeline'
              backendAzureRmOverrideSubscriptionID: 'c69268aa-c88b-494c-aa80-775984104d2a'
              backendAzureRmResourceGroupName: 'rg-gunjan-cicd'
              backendAzureRmStorageAccountName: 'xyzabcdefgh'
              backendAzureRmContainerName: 'raman'
              backendAzureRmKey: 'brijesh.tfstate'    

          - task: CmdLine@2
            displayName: Linter
            inputs:
              script: |
                tflint

          - task: CmdLine@2
            displayName: tfsec
            inputs:
              script: |
                tfsec
                     