trigger:
  - main

pool:
  name: Jasus

stages:
  - stage: planning
    displayName: raman pipeline
    jobs:
      - job: planning
        displayName: planning job
        steps:
          - task: TerraformInstaller@1
            displayName: terraform installer
            inputs:
              terraformVersion: latest

          - task: TerraformTask@5  
            displayName: terraform Init
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendAzureRmUseEntraIdForAuthentication: false
              backendServiceArm: 'newpipeline'
              backendAzureRmOverrideSubscriptionID: 'c69268aa-c88b-494c-aa80-775984104d2a'
              backendAzureRmResourceGroupName: 'rg-gunjan-cicd'
              backendAzureRmStorageAccountName: 'xyzabcdefgh'
              backendAzureRmContainerName: 'brijesh1'
              backendAzureRmKey: 'raman.tfstate'
         
  - stage: validationandplan
    displayName: validation
    jobs:
      - job: planning
        displayName: validation
        steps:
          - task: TerraformTask@5
            displayName: terraform validate
            inputs:
              provider: azurerm
              command: validate
              
          - task: TerraformTask@5
            displayName: Tarrform plan
            inputs:
              provider: azurerm
              command: plan
              environmentServiceNameAzureRM: newpipeline    
              

                  
    