trigger:
  - main

pool:
  name: Jasus

# variables:
#   svc: $(svc)
#   subsid: $(subsid)

variables:
  svc: 'newpipeline'  
  subsid: 'c69268aa-c88b-494c-aa80-775984104d2a'

parameters:
  # - name: environment
  #   type: string
  #   default: dev
  #   values:
  #     - dev
  #     - prod
  #     - preprod

  - name: init
    type: boolean 
    default: false

  - name: plan
    type: boolean
    default: false

  - name: apply
    type: boolean
    default: false
    


stages:
  - stage: planning
    displayName: raman pipeline
    jobs:
      - job: planning
        displayName: planning job
        steps:
          - task: TerraformInstaller@1
            displayName: terraform installer
            inputs:
              terraformVersion: latest

          - task: TerraformTask@5  
            displayName: terraform Init
            # condition: ${{parameters.init}}
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendAzureRmUseEntraIdForAuthentication: false
              backendServiceArm: $(svc)
              backendAzureRmOverrideSubscriptionID: $(subsid)
              backendAzureRmResourceGroupName: 'rg-gunjan-cicd'
              backendAzureRmStorageAccountName: 'xyzabcdefgh'
              backendAzureRmContainerName: 'brijesh1'
              backendAzureRmKey: 'raman.tfstate'

          - task: TerraformTask@5
            displayName: terraform Plan
            # condition: '${{parameters.plan}}'
            inputs:
              provider: azurerm
              command: plan
              environmentServiceNameAzureRM: '$(svc)'

                 
         
  - stage: validationandplan
    pool: server
    displayName: validation
    jobs:
      - job: validation
        displayName: validation
        steps:
          - task: ManualValidation@1
            displayName: manualvalidate
            inputs:
              notifyUsers: 'Brijesh@psutar43gmail.onmicrosoft.com'
              allowApproversToApproveTheirOwnRuns: false
              
  - stage: 
    displayName: apply
    jobs:
      - job: Apply
        displayName: apply
        steps:
          - task: TerraformTask@5  
            displayName: terraform Init
            # condition: ${{parameters.init}}
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendAzureRmUseEntraIdForAuthentication: false
              backendServiceArm: '$(svc)'
              backendAzureRmOverrideSubscriptionID: '$(subsid)'
              backendAzureRmResourceGroupName: 'rg-gunjan-cicd'
              backendAzureRmStorageAccountName: 'xyzabcdefgh'
              backendAzureRmContainerName: 'brijesh1'
              backendAzureRmKey: 'raman.tfstate'
          - task: TerraformTask@5
            displayName: terraform apply
            # condition: ${{parameters.apply}}
            inputs:
              provider: azurerm
              command: apply
              environmentServiceNameAzureRM: '$(svc)'
                  
              

                  
    